<?php
/** @var Ced\DevTool\Block\DevTool $block */
?>
<input type="text" placeholder="Search" id="block-search" data-mage-init='{"Ced_DevTool/js/search":{}}'/>
<table class="table-block">
    <thead>
        <tr>
            <th><?php echo __('Blocks') ?></th>
            <th><?php echo __('Handle') ?></th>
            <th><?php echo __('Associated Template') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach( $block->getBlockHandleDetails() as $bloc ): ?>
            <tr class="<?php echo ( ($row % 2 ? 'odd' : 'even')) ?>">
                <td><?php echo __($bloc['class']) ?></td>
                <td><?php echo __($bloc['handle']) ?></td>
                <td><?php echo __($bloc['template']) ?></td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
    </tbody>
</table>
