<?php
/** @var Ced\DevTool\Block\DevTool $block */
?>
<input type="text" placeholder="Search" id="events-search" data-mage-init='{"Ced_DevTool/js/search":{}}'/>
<table class="table-events">
	<thead>
		<tr>
			<th><?php echo __('Event Name') ?></th>
			<th><?php echo __('Observer Name') ?></th>
			<th><?php echo __('Observer Function') ?></th>
			<th><?php echo __('Observer Class') ?></th>
			<th><?php echo __('Call Count') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach($block->getEventDetails() as $event ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'odd' : 'even')) ?>">
				<td><?php echo __($event['event']) ?></td>
				<td><?php echo __($event['configuration']['name']) ?></td>
				<td><?php echo isset($event['configuration']['method'])?$event['configuration']['method']:'N/A' ?></td>
				<td><?php echo __($event['configuration']['instance']) ?></td>
				<td><?php echo __($event['count']) ?></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>
