<?php
/** @var Ced\DevTool\Block\DevTool $block */
$items = $block->getModelDetails();

?>
<input type="text" placeholder="Search" id="models-search"  data-mage-init='{"Ced_DevTool/js/search":{}}'/>
<table class="table-models">
    <thead>
        <tr>
            <th><?php echo __('Resource Name') ?></th>
            <th><?php echo __('Model Class') ?></th>
            <th><?php echo __('Times Instantiated') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach ($items as $item): ?>
            <tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo $item['resource_name'] ?></td>
                <td><?php echo $item['class'] ?></td>
                <td><?php echo $item['occurences'] ?></td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
    </tbody>
</table>
