<?php
/** @var Ced\DevTool\Block\DevTool $block */
?>
<input type="text" placeholder="Search" id="preference-search" data-mage-init='{"Ced_DevTool/js/search":{}}'/>
<table class="table-preference">
	<thead>
		<tr>
			<th><?php echo __('Class') ?></th>
			<th><?php echo __('Extended Class') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $block->getPreferencesDetails() as $extendedClass=>$class ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'odd' : 'even')) ?>">
				<td><?php echo __($class) ?></td>
				<td><?php echo __($extendedClass) ?></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>
