<?php
/** @var Ced\DevTool\Block\DevTool $block */
?>
<input type="text" placeholder="Search" id="query-search" data-mage-init='{"Ced_DevTool/js/search":{}}'/>
<table class="table-query">
	<thead>
		<tr>
			<th><?php echo __('Query') ?></th>
			<th><?php echo __('Time') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach($block->getQueryDetails() as $data){ ?>
			<tr class="<?php echo ( ($row % 2 ? 'odd' : 'even')) ?>">
				<td><?php echo $data->getQuery() ?></td>
				<td><?php echo $data->getElapsedSecs() ?></td>
			</tr>
			<?php $row++; ?>
		<?php } ?>
	</tbody>
</table>
