<?php
/** @var Ced\DevTool\Block\DevTool $block */
?>
<button class="button devtool-system-toggle"
        id="toggle-path-hint"
        redirecturi="<?= $block->getControllerUrl('devtool/systemtasks/togglepathhint') ?>">
    <?= $block->getTogglePathHintTitle() ?>
</button>
<button class="button devtool-system-toggle"
        id="toggle-block-hint"
        redirecturi="<?= $block->getControllerUrl('devtool/systemtasks/toggleblockhint') ?>">
    <?= $block->getToggleBlockHintTitle() ?>
</button>
<button class="button devtool-system-toggle"
        id="flush-cache"
        redirecturi="<?= $block->getControllerUrl('devtool/systemtasks/flushall') ?>">
    <?= __('Flush Cache') ?>
</button>
<button class="button devtool-system-toggle"
        id="toggle-cache"
        redirecturi="<?= $block->getControllerUrl('devtool/systemtasks/togglecache') ?>">
    <?= __('Toggle Cache') ?>
</button>

<input type="hidden" id="current-url" value="<?= $block->getCurrentUrl() ?>">
<script type="text/javascript">
	require([
		"jquery",
		"jquery/jquery.cookie",
		"mage/mage",
		"mage/cookies",
	], function($){
		(function($) {
			$('.devtool-system-toggle').click(function(){
				$(this).attr('disabled','disabled');
				$(this).html('Wait...');
				$url=$(this).attr('redirecturi');
				$returnUrl=$(this).attr('current-url');
				$.post($url,{returnUrl:$returnUrl},function(){
					location.reload();
				});
			});
		})(jQuery);	
	});	
</script>